name: ci
on:
  push:
    branches: [master]
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    name: Node.js ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: test
      run: |
        npm ci
        npm test